version: "3.7"
services: 
    db:
        container_name: db
        user: root
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
          - db-data:/var/opt/mssql/data
          - db-files:/opt/mssql/lib
        environment:
          MSSQL_SA_PASSWORD: "Admin@123"
          ACCEPT_EULA: "Y"
          MSSQL_TCP_PORT: 1433
          MSSQL_PID: HMWJ3-KY3J2-NMVD7-KG4JR-X2G8G
          MSSQL_MEMORY_LIMIT_MB: 8192
          MSSQL_CPU_LIMIT: 4
        ports:
          - "1663:1433"
        networks:
          - default
        restart: always
        logging:
          options:
            max-size: "50m"
 
    api:
         image: salary_api
         container_name: salary_api 
         build: 
              context: .
              dockerfile: Dockerfile
         environment:
              - ASPNETCORE_ENVIRONMENT=Development
              #- ASPNETCORE_URLS=http://+:2002
              #- DOTNET_USE_POLLING_FILE_WATCHER=1
              #- ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
              #- NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
              #- ASPNETCORE_CONTENTROOT=/app/Fanly.Api.HttpApi.Host/
         networks:
            - default
         #volumes:
             # - ./executive/entrypoint.sh:/app/entrypoint.sh:ro
             # - /Static:/app/Static
             # - ./certs/:/etc/ssl/
         restart: "no"
         depends_on:
            - db
         ports: 
            - "5000:80"
         logging:
              options:
                max-size: "50m"
 
volumes:
    db-data:
        external: true
    db-files:
        external: true
   