// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salary.Infrastructure.Data;

namespace Salary.Infrastructure.Migrations
{
    [DbContext(typeof(SalaryContext))]
    [Migration("20210917021017_initialsqlmig")]
    partial class initialsqlmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Salary.Core.Entities.EmployeeSalary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");


                    b.Property<string>("LastName")
                        .HasColumnType("OverTimeCalculator");

                    b.Property<long>("TotalSalary")
                       .HasColumnType("INTEGER");

                    b.Property<long>("Transportation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Allowance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("BaseSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeSalarys");
                });
#pragma warning restore 612, 618
        }
    }
}
